# Generated by Django 3.0.2 on 2021-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20210216_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='images_books', verbose_name='Изображение'),
        ),
    ]
